function param_treils = path_and_metric_struct( k,L )
%% массив путей 2 мерный массив где каждая строка обозначает ее путь-состояние,L длинна прохода
path=ones(2^(k+1),L)*5;
path_new=ones(2^(k+1),L)*5;
%% массив метрик в начальный момент времени хранится 0 на первом состоянии на остальных -бесконечность

metric=zeros(2^(k+1),1);
metric_new=zeros(2^(k+1),1);

for i=1:1:2^(k+1)
    if i==1
        metric(i,1)=0;
    else
        metric(i,1)=-1*inf;
    end
end

bit_end_rebra=ones(2^(k+1),1);

 param_treils=struct(      'path_begin', path(1:2^k,:),...
                           'path_new_begin',path_new(1:2^k,:),...
                           'metric_begin',metric(1:2^k,:),...
                           'metric_new_begin',metric_new(1:2^k,:),...
                           'last_bit_rebra_begin',bit_end_rebra(1:2^k,:),...
                           'last_bit_rebra_new_begin',bit_end_rebra(1:2^k,:),...
                           'path', path,...
                           'path_new',path_new,...
                           'metric',metric ,...
                           'metric_new',metric_new,...
                           'last_bit_rebra',bit_end_rebra*5,...
                           'last_bit_rebra_new',bit_end_rebra*5);
                       param_treils.metric(1:end,1)=-inf;
end

